global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway-service:8080"]

  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["product-service:8081"]

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8082"]

  - job_name: "inventory-service"
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      - targets: ["inventory-service:8083"]

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["order-service:8084"]

  - job_name: "payment-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["payment-service:8085"]

  - job_name: "notification-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:8086"]
